apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: imagescan
spec:
  version: v1.0.0
  homepage: https://github.com/dejanu/kubectl-imagescan
  shortDescription: Scan container images used by Pods
  description: |
    kubectl-imagescan inspects container images referenced by Pods
    to surface common issues, metadata, and signals useful for triage.
  platforms:
    - selector:
        matchLabels:
          os: linux
      uri: https://github.com/dejanu/kubectl-imagescan/releases/download/v1.0.0/kubectl-imagescan-linux-amd64.tar.gz
      sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      bin: kubectl-imagescan
    - selector:
        matchLabels:
          os: darwin
      uri: https://github.com/dejanu/kubectl-imagescan/releases/download/v1.0.0/kubectl-imagescan-darwin-amd64.tar.gz
      sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      bin: kubectl-imagescan
